# MAGENTO2
# PHUSION PHP7/APACHE REDIS MYSQL VARNISH PHPMYADMIN
# https://github.com/gaiterjones/docker-magento2
#
#
version: "3.1"

services:
    manager:
        build: ./manager/phusion
        hostname: manager
        domainname: "${APPDOMAIN}"
        volumes:
            #- "${CONTAINERDATA}/${PROJECT_NAME}/dev1:/var/www/dev"
            - "${CONTAINERDATA}/${PROJECT_NAME}/data:/home/data"
            - "${MANAGERDEV}:/home/dev"
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - wwwserver
        environment:
            SCALE_MANAGER_PROJECTNAME: "${PROJECT_NAME}"
            SCALE_CONTAINER_NAME: "${SCALE_CONTAINER_NAME}"
            PROXY_NETWORK_NAME: "${PROXY_NETWORK_NAME}"
            PROXY_TYPE: "${PROXY_TYPE}"
            APPDOMAIN: "${APPDOMAIN}"

    memcached:
        image: memcached:latest
        networks:
            - wwwserver
        depends_on:
            - manager

    php-apache:
        build:
            context: ./ubuntu/
            args:
                 MAGENTO_REPO_USERNAME: "${MAGENTO_REPO_USERNAME}"
                 MAGENTO_REPO_PASSWORD: "${MAGENTO_REPO_PASSWORD}"
                 SMTP: "${SMTP}"
                 APPDOMAIN: "${APPDOMAIN}"
        hostname: magento2
        domainname: "${APPDOMAIN}"
        expose:
            - 80
            - 443
        #ports:
        #    - "80:80"
        volumes:
            #- "${CONTAINERDATA}/${PROJECT_NAME}/dev1:/var/www/dev"
            - "${CONTAINERDATA}/${PROJECT_NAME}/data:/home/data"
            - "${CONTAINERDATA}/${PROJECT_NAME}/logs:/var/www/logs"
        networks:
            - database
            - wwwserver
        depends_on:
            - mysql
        env_file: .env

    redis_session:
        build: ./redis/session/
        networks:
            - wwwserver
        depends_on:
            - php-apache
    redis_system:
        image: redis:latest
        networks:
            - wwwserver
        depends_on:
            - php-apache
    varnish:
        build: ./varnish
        hostname: varnish
        domainname: "${APPDOMAIN}"
        #expose:
        #  - 80
        #  - 6082
        ports:
            - "80:80"
        networks:
           - wwwserver
        depends_on:
           - php-apache
        volumes:
          - "${CONTAINERDATA}/${PROJECT_NAME}/data:/home/data"
          - ./varnish/varnish.vcl:/etc/varnish/default.vcl
          - ./varnish/varnish.secret:/etc/varnish/secret
        environment:
          - CACHE_SIZE=64M

    mysql:
        image: mysql:latest
        hostname: mysql
        domainname: "${APPDOMAIN}"
        volumes:
            #- "${CONTAINERDATA}/${PROJECT_NAME}/mysql/dev1:/var/lib/mysql"
            - "${CONTAINERDATA}/${PROJECT_NAME}/data:/home/data"
        networks:
            - database
        restart: always            
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        hostname: phpmyadmin
        domainname: "${APPDOMAIN}"
        expose:
            - 80
        networks:
            - database
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_ABSOLUTE_URI: "${PMA_ABSOLUTE_URI}"

networks:
    database:
    wwwserver: